# Generated by Django 5.2.5 on 2025-09-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=255, verbose_name='Firma İsmi')),
                ('slogan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma Sloganı')),
                ('logo', models.ImageField(upload_to='firma_logo/', verbose_name='Firma Logosu')),
                ('icon', models.ImageField(upload_to='firma_icon/', verbose_name='Firma İkonu')),
                ('telefon', models.CharField(max_length=30, verbose_name='Telefon Numarası')),
                ('adres', models.CharField(max_length=255, verbose_name='Adres')),
                ('sms_yazisi', models.CharField(blank=True, max_length=255, null=True, verbose_name='SMS Yazısı')),
                ('email_onay_yazisi', models.TextField(blank=True, null=True, verbose_name='Email Onay Yazısı')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
            },
        ),
        migrations.CreateModel(
            name='FooterYazi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik_sol', models.TextField(verbose_name='Footer Sol İçeriği')),
                ('buton_yazi_sag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer Sağ Buton Yazısı')),
                ('buton_modal_icerik_sag', models.TextField(blank=True, null=True, verbose_name='Footer Sağ İçeriği')),
                ('buton_yazi_sag_iki', models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer Sağ İki Buton Yazısı')),
                ('buton_modal_icerik_sag_iki', models.TextField(blank=True, null=True, verbose_name='Footer Sağ İki İçeriği')),
            ],
            options={
                'verbose_name': 'Footer Yazısı',
                'verbose_name_plural': 'Footer Yazıları',
            },
        ),
        migrations.CreateModel(
            name='Smtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='SMTP Sunucusu')),
                ('port', models.IntegerField(verbose_name='Port Numarası')),
                ('username', models.CharField(max_length=255, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(max_length=255, verbose_name='Şifre')),
                ('use_tls', models.BooleanField(default=True, verbose_name='TLS Kullan')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='SSL Kullan')),
            ],
            options={
                'verbose_name': 'SMTP Ayarı',
                'verbose_name_plural': 'SMTP Ayarları',
            },
        ),
    ]
