# Generated by Django 5.2.5 on 2025-09-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='email_dogrulama',
            field=models.BooleanField(default=False, verbose_name='Email Doğrulama'),
        ),
    ]
