# Generated by Django 5.2.5 on 2025-09-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0002_firma_email_dogrulama'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='termin_onay_yazisi',
            field=models.TextField(blank=True, null=True, verbose_name='Termin Bestätigung Yazısı'),
        ),
    ]
