# Generated by Django 5.2.5 on 2025-09-08 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusteriFormModelDurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, unique=True)),
                ('sira', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Form Durumu',
                'verbose_name_plural': 'Form Durumları',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sehir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('il', models.CharField(max_length=255, verbose_name='Şehir Adı')),
                ('ilce', models.CharField(max_length=255, verbose_name='İlçe Adı')),
                ('posta_kodu', models.CharField(max_length=10, verbose_name='Posta Kodu')),
            ],
            options={
                'verbose_name': 'Şehir',
                'verbose_name_plural': 'Şehirler',
            },
        ),
        migrations.CreateModel(
            name='SigortaSirket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=255, unique=True)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='sigorta_sirketleri/')),
                ('sira', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sigorta Şirketi',
                'verbose_name_plural': 'Sigorta Şirketleri',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MusteriFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('randevu_tarihi', models.DateTimeField()),
                ('firma_adi', models.CharField(max_length=255)),
                ('musteri_isim', models.CharField(max_length=255)),
                ('musteri_soyisim', models.CharField(max_length=255)),
                ('musteri_dogum_tarihi', models.DateField()),
                ('adres', models.TextField()),
                ('sehir', models.CharField(blank=True, max_length=255, null=True)),
                ('telefon', models.CharField(blank=True, max_length=50, null=True)),
                ('telefon_onayli_mi', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('email_onayli_mi', models.BooleanField(default=False)),
                ('medeni_durum', models.CharField(choices=[('Bekar', 'Ledig'), ('Evli', 'Verheiratet'), ('Boşanmış', 'Geschieden'), ('Dul', 'Verwitwet'), ('Kayıtlı Ortaklık', 'Eingetragene Partnerschaft'), ('Diğer', 'Sonstiges')], default='Bekar', max_length=50)),
                ('aile_durumu_aktif', models.BooleanField(default=False)),
                ('aile_durumu_s', models.BooleanField(default=False)),
                ('aile_cocuk_sayisi', models.IntegerField(blank=True, null=True)),
                ('sigorta', models.CharField(blank=True, choices=[('Özel', 'Privat'), ('Yasal', 'Gesetzlich')], max_length=255, null=True)),
                ('sigorta_ek_yazi', models.TextField(blank=True, null=True)),
                ('sigorta_katki_payi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sigorta_baslangic_tarihi', models.DateField(blank=True, null=True)),
                ('sigorta_tarife_vadesi', models.DateField(blank=True, null=True)),
                ('sigorta_katilim_payi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es_cocuk_sigorta', models.CharField(blank=True, choices=[('Özel/Ortak Sigortalı', 'Privat/Mitversichert'), ('Yasal/Ortak Sigortalı', 'Gesetzlich/Mitversichert')], max_length=255, null=True)),
                ('es_yasi', models.IntegerField(blank=True, null=True)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('durum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayfalar.musteriformmodeldurum')),
                ('posta_kodu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayfalar.sehir')),
                ('sigorta_sirket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayfalar.sigortasirket')),
            ],
            options={
                'verbose_name': 'Müşteri Formu',
                'verbose_name_plural': 'Müşteri Formları',
            },
        ),
        migrations.CreateModel(
            name='EmailGonderimleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gonderilen_email', models.TextField()),
                ('gonderim_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayfalar.musteriformmodel')),
            ],
            options={
                'verbose_name': 'E-Posta Gönderimi',
                'verbose_name_plural': 'E-Posta Gönderimleri',
            },
        ),
        migrations.CreateModel(
            name='MusteriFormModelCocukYasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocuk_yasi', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayfalar.musteriformmodel')),
            ],
            options={
                'verbose_name': 'Çocuk Yaşı',
                'verbose_name_plural': 'Çocuk Yaşları',
            },
        ),
        migrations.CreateModel(
            name='MusteriFormModelNot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_icerigi', models.TextField(blank=True, null=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, null=True)),
                ('son_guncelleme_tarihi', models.DateTimeField(auto_now=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayfalar.musteriformmodel')),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Notu',
                'verbose_name_plural': 'Form Notları',
            },
        ),
        migrations.CreateModel(
            name='MusteriFormModelPaylasim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, null=True)),
                ('son_guncelleme_tarihi', models.DateTimeField(auto_now=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayfalar.musteriformmodel')),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Paylaşımı',
                'verbose_name_plural': 'Form Paylaşımları',
            },
        ),
    ]
