# Generated by Django 5.2.5 on 2025-09-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteriformmodel',
            name='sabit_telefon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
