# Generated by Django 5.2.5 on 2025-09-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0002_musteriformmodel_sabit_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteriformmodel',
            name='musteri_cinsiyet',
            field=models.CharField(blank=True, choices=[('Erkek', 'Herr'), ('Kadın', 'Frau')], max_length=10, null=True),
        ),
    ]
