# Generated by Django 5.2.5 on 2025-09-12 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0003_musteriformmodel_musteri_cinsiyet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigortaAltSirket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=255)),
                ('sirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayfalar.sigortasirket')),
            ],
            options={
                'verbose_name': 'Sigorta Alt Şirketi',
                'verbose_name_plural': 'Sigorta Alt Şirketleri',
            },
        ),
        migrations.AlterField(
            model_name='musteriformmodel',
            name='sigorta_tarife_vadesi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayfalar.sigortaaltsirket'),
        ),
    ]
