# Generated by Django 5.2.5 on 2025-09-12 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0004_sigortaaltsirket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteriformmodel',
            name='sigorta_sirket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sigorta_alt_sirket', to='sayfalar.sigortasirket'),
        ),
    ]
