# Generated by Django 5.2.5 on 2025-09-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0006_alter_musteriformmodel_sigorta_sirket'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteriformmodel',
            name='es_calisma_durumu',
            field=models.CharField(blank=True, choices=[('Çalışan', 'Arbeitnehmer'), ('Kendi İşinin Patronu', 'Selbstständig')], max_length=255, null=True),
        ),
    ]
