# Generated by Django 5.2.5 on 2025-09-12 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0007_musteriformmodel_es_calisma_durumu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sigortaaltsirket',
            options={'ordering': ['sira', 'id'], 'verbose_name': 'Sigorta Alt Şirketi', 'verbose_name_plural': 'Sigorta Alt Şirketleri'},
        ),
        migrations.AddField(
            model_name='sigortaaltsirket',
            name='sira',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sigortaaltsirket',
            name='sirket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='altlar', to='sayfalar.sigortasirket'),
        ),
    ]
