# Generated by Django 5.2.5 on 2025-09-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0008_alter_sigortaaltsirket_options_sigortaaltsirket_sira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteriformmodel',
            name='randevu_tipi',
            field=models.CharField(blank=True, choices=[('Video', 'Video'), ('Telefon', 'Telefon'), ('Vor Ort', 'Vor Ort')], max_length=20, null=True),
        ),
    ]
