# Generated by Django 5.2.5 on 2025-09-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0009_musteriformmodel_randevu_tipi'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteriformmodel',
            name='calisma_durumu',
            field=models.CharField(blank=True, choices=[('Arbeitnehmer', 'Arbeitnehmer'), ('Selbstständig', 'Selbstständig')], max_length=50, null=True),
        ),
    ]
