# Generated by Django 5.2.5 on 2025-09-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0010_musteriformmodel_calisma_durumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteriformmodel',
            name='posta_kodu_raw',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
