# Generated by Django 5.2.5 on 2025-09-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0011_musteriformmodel_posta_kodu_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigortasirket',
            name='kapsam',
            field=models.CharField(choices=[('Privat', 'Privat'), ('Gesetzlich', 'Gesetzlich'), ('Beides', 'Beides')], default='Beides', max_length=10),
        ),
        migrations.AlterField(
            model_name='musteriformmodel',
            name='sigorta',
            field=models.CharField(blank=True, choices=[('Özel', 'Privat'), ('Yasal', 'Gesetzlich'), ('Sigorta Yok', 'Nicht Versichert')], max_length=255, null=True),
        ),
    ]
