# Generated by Django 5.2.5 on 2025-09-18 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0012_sigortasirket_kapsam_alter_musteriformmodel_sigorta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('FORM_CREATE', 'Form Oluşturuldu'), ('FORM_UPDATE', 'Form Güncellendi'), ('FORM_DELETE', 'Form Silindi'), ('STATUS_CHANGE', 'Durum Değiştirildi'), ('FORM_SHARE', 'Form Paylaşıldı'), ('EMAIL_SEND', 'E-posta Gönderildi'), ('NOTE_ADD', 'Not Eklendi'), ('NOTE_UPDATE', 'Not Güncellendi'), ('NOTE_DELETE', 'Not Silindi'), ('USER_LOGIN', 'Kullanıcı Girişi'), ('USER_LOGOUT', 'Kullanıcı Çıkışı'), ('USER_CREATE', 'Kullanıcı Oluşturuldu'), ('USER_UPDATE', 'Kullanıcı Güncellendi'), ('USER_DELETE', 'Kullanıcı Silindi'), ('SETTINGS_UPDATE', 'Ayarlar Güncellendi'), ('OTHER', 'Diğer')], max_length=20, verbose_name='Aksiyon Tipi')),
                ('severity', models.CharField(choices=[('INFO', 'Bilgi'), ('WARNING', 'Uyarı'), ('ERROR', 'Hata'), ('SUCCESS', 'Başarılı')], default='INFO', max_length=10, verbose_name='Önem Derecesi')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Tarayıcı Bilgisi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Detaylar (JSON)')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Eski Değerler')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Yeni Değerler')),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('related_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayfalar.musteriformmodel', verbose_name='İlgili Form')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_logs', to=settings.AUTH_USER_MODEL, verbose_name='İlgili Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sistem Logu',
                'verbose_name_plural': 'Sistem Logları',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='sayfalar_sy_timesta_c54a69_idx'), models.Index(fields=['kullanici'], name='sayfalar_sy_kullani_989949_idx'), models.Index(fields=['action_type'], name='sayfalar_sy_action__33e6eb_idx'), models.Index(fields=['severity'], name='sayfalar_sy_severit_35298d_idx')],
            },
        ),
    ]
