# Generated by Django 5.2.5 on 2025-09-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0013_systemlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='action_type',
            field=models.CharField(choices=[('FORM_CREATE', 'Form Oluşturuldu'), ('FORM_UPDATE', 'Form Güncellendi'), ('FORM_DELETE', 'Form Silindi'), ('STATUS_CHANGE', 'Durum Değiştirildi'), ('FORM_SHARE', 'Form Paylaşıldı'), ('EMAIL_SEND', 'E-posta Gönderildi'), ('NOTE_ADD', 'Not Eklendi'), ('NOTE_UPDATE', 'Not Güncellendi'), ('NOTE_DELETE', 'Not Silindi'), ('USER_LOGIN', 'Kullanıcı Girişi'), ('USER_LOGOUT', 'Kullanıcı Çıkışı'), ('USER_CREATE', 'Kullanıcı Oluşturuldu'), ('USER_UPDATE', 'Kullanıcı Güncellendi'), ('USER_DELETE', 'Kullanıcı Silindi'), ('PROFILE_UPDATE', 'Profil Güncellendi'), ('PASSWORD_CHANGE', 'Şifre Değiştirildi'), ('SETTINGS_UPDATE', 'Ayarlar Güncellendi'), ('OTHER', 'Diğer')], max_length=20, verbose_name='Aksiyon Tipi'),
        ),
    ]
