# Generated by Django 5.2.5 on 2025-09-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0014_alter_systemlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteriformmodel',
            name='es_cocuk_sigorta',
            field=models.CharField(blank=True, choices=[('Özel', 'Privat'), ('Gesetzlich', 'Gesetzlich'), ('Özel/Ortak Sigortalı', 'Privat/mitversichert'), ('Yasal/Ortak Sigortalı', 'Gesetzlich/mitversichert')], max_length=255, null=True),
        ),
    ]
